### NAMED BlinkLights.action

# Request
float64 rate
int8 duration
string color
bool striplights
bool headlights
bool glowlights
---
# Response
bool finished
string debug_msg
---
# Feedback
float64 time_remaining
